### ISSUE TITLE
protocol not supported error when I executing 'myframe.sh'

### ISSUE THREAD

**Issue by moshangqingfeng** [seemoo-lab/mobisys2018_nexmon_software_defined_radio#23] opened 2024-04-23 07:19 UTC
Sorry guys,

I'm trying to install this sdr tool on a rpi3B+
when I executing myframe.sh, it reports a long list of error, repeating:
nex_init_netlink: socket error (93: Protocol not supported) nex_init_netlink: socket error (93: Protocol not supported) nex_init_netlink: bind error (9: Bad file descriptor) nex_init_netlink: connect error (9: Bad file descriptor) ERR (__nex_driver_netlink): no valid answer received
My kernel version is 5.10,firmware version is 7.45.154.
I have no idea and stuck on this for several days, anyone can provide some hints?

**Comment by jlinktu** [comment] 2024-04-23 08:31
Duplicate of #8

**Closed as not planned by jlinktu** 2024-04-23 08:31 UTC
